frr defaults traditional
hostname R1
service integrated-vtysh-config
!

interface eth1
 ip address 10.0.12.1/30
 ip ospf area 0
!

interface eth2
 ip address 10.0.13.1/30
 ip ospf area 0
!

interface eth3
 ip address 192.168.10.1/24
!

router ospf
 ospf router-id 1.1.1.1
 passive-interface eth3
!

line vty
!
