frr defaults traditional
hostname R2
service integrated-vtysh-config
!

interface eth1
 ip address 10.0.12.2/24
 ip ospf area 0
!

interface eth2
 ip address 10.0.23.2/24
 ip ospf area 0
!

router ospf
 ospf router-id 2.2.2.2
!

line vty
!

